# Generated by Django 4.2.7 on 2023-11-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daftarPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, verbose_name='Nama Mahasiswa')),
                ('sekolah', models.CharField(max_length=50, verbose_name='Asal Sekolah')),
                ('jurusan', models.CharField(max_length=50, verbose_name='Jurusan')),
                ('hp', models.CharField(max_length=15, verbose_name='No HP')),
                ('alamat', models.CharField(max_length=100, verbose_name='Alamat')),
            ],
        ),
    ]
